const appname = "Reigns Sport";
const appversion = "Version 1.0.0";
const credits = "@MP Team";
const email = "Email";
const emailHint = "admin@admin.com";
const password = "Mật khẩu";
const passwordHint = "******";
const retypePassword = "Xác nhận mật khẩu";
const name = "Họ tên";
const nameHint = "Nguyen Truong An";
const forgetPass = "Quên mật khẩu";
const login = "Đăng nhập";
const logout = "Đăng xuất";
const signUp = "Đăng ký";
const createNewAccount = "hoặc, tạo một tài khoản mới";
const loginWidth = "Đăng nhập với";
const privacyPolicy = "Chính sách bảo mật";
const loggedIn = "Đăng nhập thành công";
const loggedOut = "Logged out successfully";
const termAndCond = "Các điều khoản";
const alreadyHaveAccount = "Bạn đã có tài khoản ?";
const home = "Trang chủ",
    categories = "Loại sản phẩm",
    cart = "Giỏ hàng",
    account = "Tài khoản";
const searchAnything = "Nhập tên sản phẩm...",
    todayDeal = "Today's Deal...",
    flashSale = "Flash Sale",
    topSellers = "Top Sellers",
    brand = "Brand",
    topCategories = "Top Categories",
    womenDress = "Women Dress",
    girlWatches = "Girl Watches",
    mobilePhone = "Mobile Phone",
    boysGlasses = "Boys Glasses",
    tShirts = "TShirts",
    girlsDress = "Girls Dresses",
    featuredProduct = "Featured Product",
    featuredCategories = "Featured Categories";
const womenClothing = "Women Clothing",
    menClothingFashion = "Men Clothing & Fashion",
    compAccess = "Computer & Accessories",
    automobile = "Automobile",
    kidToys = "Kids & Toys",
    sports = "Sports",
    jewelery = "Jewelery",
    cellphone = "Cellphone & Tab",
    furniture = "Furniture";
const video = "Video",
    reviews = "Reviews",
    sellerPolicy = "Seller Policy",
    returnPolicy = "Return Policy",
    supportPolicy = "Support Policy",
    productsYouMayLike = "Sản phẩm liên quan";
const wishList = "Danh mục ưa thích", orders = "Danh sách đơn hàng", messages = "Chăm sóc khách hàng", oldPass = "Mật khẩu cũ ", newPass = "Mật khẩu mới";
const paypal = "Paypal", stripe = "Stripe", cod = "Cash on delivery";